# Generated by Django 4.1 on 2022-08-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=200)),
                ('Lname', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=50)),
                ('Age', models.PositiveIntegerField(max_length=50)),
                ('Address', models.TextField()),
                ('phone', models.CharField(max_length=10)),
                ('religion', models.CharField(max_length=50)),
                ('nation', models.CharField(max_length=50)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
