# Generated by Django 4.1 on 2022-08-31 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdetails',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='contactdetails',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='contactdetails',
            old_name='Fname',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='contactdetails',
            old_name='Lname',
            new_name='lname',
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
