# Generated by Django 4.1 on 2022-08-31 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_address_contactdetails_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactdetails',
            options={'ordering': ['-updated', 'created']},
        ),
    ]
