# Generated by Django 4.1 on 2022-09-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_contactdetails_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='added_by',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
