# Generated by Django 4.1 on 2022-09-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_contactdetails_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='photo',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
